### ISSUE TITLE
图片的相对路径有点奇怪

### ISSUE THREAD

**Issue by jareguo** [fireball-x/docs#12]
我提交了这个文档后， github 里是能看到图片的：https://github.com/fireball-x/docs/blob/93ab0e8520d850e0c4c80c697416827a21492936/source/zh/scripting/component/access.md
文档是 access.md 图片路径是 ./img/xxx.png
但是在[文档网站](http://docs.fireball-x.com/zh/scripting/component/access/)上看不到，网站上把 img 解析成了目录 access/img/xxx.png。但是 access 目录并不存在……
这个问题要怎么改比较好？如果图片路径用 ../img/xxx.png，又会导致 github 里看不到图片

**Comment by nantas** [comment]
hexo 不如 jekyll 的地方就在于不提供'permalink.html', 只提供'permalink/index.html'

所以要想让一张图在 github 和网站上都能显示，只能用绝对路径或外链了。

外链的话，我一般的做法是打开一个 new issue 窗口，把要贴得图片拖进去，然后拷贝图片的链接地址到正在编辑的文档中。
