### ISSUE TITLE
文档用的图片可以都贴在这里

### ISSUE THREAD

**Issue by nantas** [fireball-x/docs#21]
在 github 编辑环境下，上传图片最快的选择就是拖到 issue 里，然后直接黏贴图片地址到文档中。

这里用来收集所有文档网站需要的图片，直接把本地图片拖到回复窗口，然后复制好图片地址（markdown 格式都帮你写好了），再点 comment 提交就可以了。

**Comment by wizcas** [comment]
收到，thx!

**Comment by wizcas** [comment]
![get-fireball-01](https://cloud.githubusercontent.com/assets/2867434/6845991/1cf31184-d3f5-11e4-9a8f-7534488da91a.png)
![get-fireball-02](https://cloud.githubusercontent.com/assets/2867434/6845993/1d201148-d3f5-11e4-968c-7f725283c83f.png)
![get-fireball-03](https://cloud.githubusercontent.com/assets/2867434/6845992/1d1f3890-d3f5-11e4-8243-8c88571f1a2f.png)

**Comment by wizcas** [comment]
![get-fireball-02](https://cloud.githubusercontent.com/assets/2867434/6846084/3bf9c8ec-d3f6-11e4-852e-ad5defde3b0a.png)
![get-fireball-03](https://cloud.githubusercontent.com/assets/2867434/6846085/3c0a631e-d3f6-11e4-9108-d6d809434549.png)
![get-fireball-01](https://cloud.githubusercontent.com/assets/2867434/6846086/3cc070fa-d3f6-11e4-8f92-2b00d4ba0a9f.png)

**Comment by wizcas** [comment]
![new-project-01](https://cloud.githubusercontent.com/assets/2867434/6851104/f49912b0-d417-11e4-8338-9b72b18df4a7.png)
![new-project-02](https://cloud.githubusercontent.com/assets/2867434/6851105/f5123dd4-d417-11e4-9399-3ea81c0fd3b0.png)

**Comment by wizcas** [comment]
![new-project-01](https://cloud.githubusercontent.com/assets/2867434/6866116/eb94b686-d4af-11e4-9233-2032a641c0f8.png)

**Comment by wizcas** [comment]
![new-project-02](https://cloud.githubusercontent.com/assets/2867434/6866397/b26ccc38-d4b2-11e4-89b0-91bc1d3f6d09.png)

**Comment by wizcas** [comment]
![editor-overview-intro](https://cloud.githubusercontent.com/assets/2867434/6872425/119047e0-d4e4-11e4-9fb4-0af7cf25c7cc.png)
