### ISSUE TITLE
中文下切换英文变成 404

### ISSUE THREAD

**Issue by jareguo** [fireball-x/docs#8]
在中文页面，http://docs.fireball-x.com/zh/index.html
点击 English，网址会变成 http://docs.fireball-x.com/zh/zh/index.html
就 duang ~~~~

**Comment by nantas** [comment]
补一个参考资料，最终我们需要 match 的条件有：以 zh 打头的，或包含有/zh/的，需要用`/(^|\/)zh\//`这样得格式，来源：http://stackoverflow.com/questions/13199118/regex-line-start-in-character-set
